defaults:
  - env/robotwin_place_empty_cup@env.train
  - env/robotwin_place_empty_cup@env.eval
  - model/pi0@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/
    
cluster:
  num_nodes: 1
  component_placement:
    actor, env, rollout: 0-7

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "robotwin_grpo_openpi"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: True
  val_check_interval: 20
  save_interval: 20

  resume_dir: null # Optional: path to a saved checkpoint directory, such as 'checkpoints/global_step_10'. If not None, it will be used to resume training.
  ckpt_path: null  # Optional: path to a .pt checkpoint. If not None, it will be loaded after the model is instantiated (for evaluation).

algorithm:
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 8

  rollout_epoch: 8
  eval_rollout_epoch: 1 # set eval_rollout_epoch > 0 when enable runner.only_eval or runner.val_check_interval > 0

  reward_type: action_level
  logprob_type: token_level
  entropy_type: token_level

  adv_type: grpo
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 1.0
  gae_lambda: 0.95

  reward_coef: 5.0
  filter_rewards: True
  rewards_lower_bound: 0.5
  rewards_upper_bound: 4.5

  # params for rollout
  sampling_params:
    do_sample: True
    temperature_train: 1.6
    temperature_eval: -1 # -1 means do_sample=False during evaluation
    top_k: -1
    top_p: 1.0
    repetition_penalty: 1.0

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 512
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: True

  # Override the default values in env/robotwin_place_empty_cup
  train:
    total_num_envs: 128
    reward_coef: ${algorithm.reward_coef}
    max_episode_steps: 200
    max_steps_per_rollout_epoch: 200
    group_size: ${algorithm.group_size}
    assets_path: "/path/to/robotwin_assets"
    seeds_path: ${oc.env:REPO_PATH}/rlinf/envs/robotwin/seeds/train_seeds.json
    center_crop: False
    task_config:
      embodiment: [aloha-agilex]
      camera:
        collect_wrist_camera: true
  eval:
    total_num_envs: 128
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 200
    reward_coef: ${algorithm.reward_coef}
    max_steps_per_rollout_epoch: 200
    group_size: 1
    use_fixed_reset_state_ids: True
    is_eval: True
    assets_path: "/path/to/robotwin_assets"
    seeds_path: ${oc.env:REPO_PATH}/rlinf/envs/robotwin/seeds/eval_seeds.json
    center_crop: False
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval
    task_config:
      embodiment: [aloha-agilex]
      camera:
        collect_wrist_camera: true

rollout:
  group_name: "RolloutGroup"
  backend: "huggingface"
  enable_offload: True
  pipeline_stage_num: 1
  model:
    model_path: ${actor.model.model_path}
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 32
  global_batch_size: 1024
  seed: 1234
  enable_offload: True

  # Override the default values in model/openpi
  model:
    model_path: "/path/to/model/RLinf-Pi0-SFT"
    num_action_chunks: 50 # interface for the env
    action_dim: 14
    use_proprio: True
    add_value_head: True
    num_steps: 5
    openpi:
      config_name: "pi0_aloha_robotwin"
      num_images_in_input: 3
      train_expert_only: True
      detach_critic_input: True

  optim:
    lr: 2.5e-5
    value_lr: 1.55e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    weight_decay: 1e-10
    clip_grad: 1.0
    total_training_steps: 30000
    lr_warmup_steps: 1000
    lr_scheduler: "cosine"
    num_cycles: 0.5
    min_lr: 2.5e-6

  # Override the default values in training_backend/fsdp
  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: True
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
