simulator_type: maniskill
auto_reset: ${algorithm.auto_reset}
ignore_terminations: ${algorithm.ignore_terminations}
use_rel_reward: True
reward_mode: raw
seed: 0
# wrap_obs_mode options:
#   - "simple": Simplified mode, directly wraps observations, supports "state" and "rgb" only
#   - "vla": VLA mode (default), uses complex observation extraction logic, supports all obs_mode including "rgb+segmentation"
wrap_obs_mode: simple
num_group: ${algorithm.num_group_envs}
group_size: ${algorithm.group_size}
use_fixed_reset_state_ids: ${algorithm.use_fixed_reset_state_ids}
max_episode_steps: 50
only_eval: False
num_envs: ${multiply:${algorithm.group_size}, ${algorithm.num_group_envs}}

video_cfg:
  save_video: False
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  id: "PickCube-v1"
  num_envs: ${multiply:${algorithm.group_size}, ${algorithm.num_group_envs}}
  # obs_mode options:
  #   - "state": State only, for MLP models (no images)
  #   - "rgb": RGB images, for CNN models
  #   - "rgb+segmentation": RGB images + segmentation masks
  obs_mode: ${algorithm.obs_mode}
  control_mode: None
  sim_backend: "gpu"
  sim_config:
    sim_freq: 100
    control_freq: 20
  max_episode_steps: ${env.train.max_episode_steps}
  sensor_configs:
    shader_pack: "default"
    width: 64
    height: 64
  render_mode: all
