simulator_type: maniskill
auto_reset: True
ignore_terminations: True
use_rel_reward: True
reward_mode: raw
# wrap_obs_mode options:
#   - "simple": Simplified mode, directly wraps observations, supports "state" and "rgb" only
#   - "vla": VLA mode (default), uses complex observation extraction logic, supports all obs_mode including "rgb+segmentation"
wrap_obs_mode: simple
seed: 0
num_group: ${env.eval.num_envs}
group_size: 1
use_fixed_reset_state_ids: True
num_envs: 32
only_eval: True

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/eval

init_params:
  id: "PickCube-v1"
  num_envs: ${env.eval.num_envs}
  # obs_mode options:
  #   - "state": State only, for MLP models (no images)
  #   - "rgb": RGB images, for CNN models
  #   - "rgb+segmentation": RGB images + segmentation masks
  obs_mode: ${env.train.init_params.obs_mode}
  control_mode: None
  sim_backend: "gpu"
  sim_config: ${env.train.init_params.sim_config}
  max_episode_steps: ${env.train.init_params.max_episode_steps}
  sensor_configs: ${env.train.init_params.sensor_configs}
  render_mode: all